### PR TITLE
Project package refactor

### LINKED ISSUE #6: Update Project class to implement more meaningful features of projects

### PR DESCRIPTION
**Pull request by T-Fang**
Refactor and Update attributes and methods in Project Package

### CODE REVIEW

**Comment by GeNiaaz** [comment]
For the Leader Object, you want to make it an instance of a Person? Such that it can contain email, address etc. I have included that in my implementation of Teammate. Lemme change that to Person then maybe your Leader can be an instance of Person too. This way you dun have to create email classes etc for the Leader

**Comment by T-Fang** [comment]
> For the Leader Object, you want to make it an instance of a Person? Such that it can contain email, address etc. I have included that in my implementation of Teammate. Lemme change that to Person then maybe your Leader can be an instance of Person too. This way you dun have to create email classes etc for the Leader

Maybe we want to wait for Lucas to implement the association class and make Leader class a subclass of association?

**Review by GeNiaaz — COMMENTED** [review]
Alright, sounds good 👍

**Review by GeNiaaz — APPROVED** [review]
Looks good, will await Lucas's implementation of the Participation class to see how an instance of Leader can be used

**Pull request merged**
